/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Myproject;

import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sansk
 */
public class AdminPan extends javax.swing.JFrame {
PreparedStatement pst,pst1,pst2,pst3,pst4;
    Connection con;
    ResultSet rs,rs1,rs3,rs4;
   
     public static boolean isStringOnlyAlphabet(String str) 
    { 
        return ((str != null) 
                && (!str.equals("")) 
                && (str.matches("^[A-Z a-z]*$"))); 
    } 
     public boolean isValid(String s) {
    String n = ".*[0-9].*";
    String a = ".*[a-z].*";
    return s.matches(n) && s.matches(a);
     }
   public boolean isValid1(String s1) {
    String n1 = "^[0-9]*$";
    return s1.matches(n1);
   
    
   
   
}
    public AdminPan() {
          
          setIcon();
        try{
      con=DriverManager.getConnection("jdbc:mysql://localhost:3306/information?serverTimezone=IST","root","");
      System.out.println("connect");
        initComponents();
        Statement s=con.createStatement();
        
        rs=s.executeQuery("select*from staff");
        jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        rs1=s.executeQuery("select *from stud_info");
        jTable1.setModel(DbUtils.resultSetToTableModel(rs1));
        
        rs3=s.executeQuery("select*from pc");
        jTable3.setModel(DbUtils.resultSetToTableModel(rs3));
        rs4=s.executeQuery("select*from master1 order by year ");
        jTable4.setModel(DbUtils.resultSetToTableModel(rs4));
        Statement st=con.createStatement();
        ResultSet rs5=st.executeQuery("select pc_no from pc order by pc_no");
        while(rs5.next())
        {
            jComboBox2.addItem(""+rs5.getInt("pc_no"));
        }
        int a[]={1,2,3};
        jComboBox3.addItem(""+a[0]);
         jComboBox3.addItem(""+a[1]);
          jComboBox3.addItem(""+a[2]);
        }
        catch(SQLException s)
        {
            System.out.println(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 153));
        jTabbedPane1.setForeground(new java.awt.Color(0, 102, 153));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jPanel1.setLayout(null);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(153, 204, 255));
        jTable1.setForeground(new java.awt.Color(51, 51, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr_no", "Enrollment ", "Name", "Year", "Batch", "Subject", "Date", "Log in", "Log out", "PC_NO", "Unique_no"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(20);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(190, 40, 1070, 530);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("*FOR UPDATED RECORDS PLEASE RESTART THE APPLICATION!!");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(80, 670, 860, 22);

        jTabbedPane1.addTab("STUDENT ATTENDANCE RECORDS", jPanel1);

        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("PC_NO:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(12, 101, 101, 57);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("PROCESSOR:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(12, 165, 150, 50);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("MEMORY:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(12, 234, 130, 42);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("GRAPHICS:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(12, 297, 140, 54);
        jPanel3.add(jTextField5);
        jTextField5.setBounds(180, 110, 160, 46);
        jPanel3.add(jTextField6);
        jTextField6.setBounds(180, 170, 160, 50);
        jPanel3.add(jTextField7);
        jTextField7.setBounds(180, 235, 160, 50);
        jPanel3.add(jTextField8);
        jTextField8.setBounds(180, 300, 160, 50);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 153));
        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(10, 390, 87, 37);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 153));
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(160, 390, 130, 37);

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setRowHeight(30);
        jScrollPane3.setViewportView(jTable3);

        jScrollPane8.setViewportView(jScrollPane3);

        jPanel3.add(jScrollPane8);
        jScrollPane8.setBounds(350, 10, 840, 570);

        jTabbedPane1.addTab("COMPUTER DETAILS", jPanel3);

        jPanel2.setLayout(null);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 200, 42));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Staff_id:");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 86, 42));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 200, 44));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Name:");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 65, 35));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 200, 44));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Password:");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 142, 100, 52));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 200, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Subject:");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 100, 37));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel15.setText("What is your favourite Color?:");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 273, -1, 43));
        jPanel7.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 180, 43));

        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 102, 153));
        jButton10.setText("ADD");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 110, 50));

        jButton11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 102, 153));
        jButton11.setText("DELETE");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 140, 50));

        jPanel2.add(jPanel7);
        jPanel7.setBounds(0, 0, 460, 530);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable2.setRowHeight(30);
        jScrollPane6.setViewportView(jTable2);

        jScrollPane5.setViewportView(jScrollPane6);

        jPanel2.add(jScrollPane5);
        jScrollPane5.setBounds(510, 0, 710, 530);

        jTabbedPane1.addTab("STAFF RECORDS", jPanel2);

        jPanel4.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setText("ENROLLMENT :");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(2, 55, 220, 41);
        jPanel4.add(jTextField10);
        jTextField10.setBounds(250, 60, 152, 41);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel11.setText("NAME:");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(0, 130, 169, 34);

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField11);
        jTextField11.setBounds(250, 130, 150, 40);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel12.setText("BATCH:");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(0, 200, 127, 36);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        jPanel4.add(jComboBox1);
        jComboBox1.setBounds(250, 200, 152, 36);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel13.setText("PC_NO:");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(0, 330, 100, 36);

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel4.add(jComboBox2);
        jComboBox2.setBounds(250, 330, 152, 36);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 153));
        jButton5.setText("ADD");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(10, 470, 105, 57);

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 102, 153));
        jButton6.setText("DELETE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(250, 470, 150, 57);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setText("YEAR:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(0, 260, 127, 40);

        jComboBox3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox3);
        jComboBox3.setBounds(250, 260, 152, 40);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel18.setText("YEAR OF ADMISSION:");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(0, 400, 250, 50);

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField9);
        jTextField9.setBounds(260, 402, 140, 40);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable4.setRowHeight(30
        );
        jTable4.setRowMargin(1
        );
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(480, 50, 767, 567);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 153));
        jButton1.setText("UPDATE");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(120, 545, 130, 50);

        jTabbedPane1.addTab("MASTER STUDENT DETAILS", jPanel4);

        jPanel5.setLayout(null);

        jButton7.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 102, 153));
        jButton7.setText("FILTER BY ENROLMENT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7);
        jButton7.setBounds(360, 20, 420, 87);

        jButton8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 102, 153));
        jButton8.setText("FILTER BY SUBJECT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8);
        jButton8.setBounds(360, 150, 430, 93);

        jButton9.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 102, 153));
        jButton9.setText("FILTER BY DATE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9);
        jButton9.setBounds(360, 280, 430, 97);

        jTabbedPane1.addTab("FILTERS", jPanel5);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 102, 153));
        jButton12.setText("DELETE ALL RECORDS");
        jPanel8.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 460, 110));

        jButton13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton13.setForeground(new java.awt.Color(0, 102, 153));
        jButton13.setText("DELETE BY YEAR OF ADMISSION");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 460, 120));

        jTabbedPane1.addTab("DELETE RECORDS", jPanel8);

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Smart Lab Assitant");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 480, 90));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("-");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 30, 40, 50));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("X");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 30, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1504, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        int row = jTable3.getSelectedRow();
        if(row<0) 
        {
            JOptionPane.showMessageDialog(this,  "Select specific row to delete"); 
        }
        else{
        String eve = (String)jTable3.getModel().getValueAt(row, 0).toString();
        String delRow = "delete from pc where pc_no="+eve;
        try {
            pst = con.prepareStatement(delRow);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Deleted selected row successfully!!!!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,  e.getMessage());
        }
        
        model.removeRow(row);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      try{
            DefaultTableModel model=(DefaultTableModel)jTable3.getModel();
            
            System.out.println("Add");
            String pc=jTextField5.getText();
            System.out.println(pc);
              double i=Double.parseDouble(pc);
            String pro=jTextField6.getText();
            System.out.println(pro);
              double i1=Double.parseDouble(pro);
            String mem=jTextField7.getText();
            System.out.println(mem);
              double i3=Double.parseDouble(mem);
            String graph=jTextField8.getText();
            System.out.println(graph);
              double i4=Double.parseDouble(graph);
           
            
            
             
            String q="insert into pc values(?,?,?,?)";
            System.out.println("PrepareStatement");
            pst1=con.prepareStatement(q);

            pst1.setString(1,pc);
            pst1.setString(2,pro);
            pst1.setString(3,mem);
            pst1.setString(4,graph);
           
            pst1.execute();
            model.addRow(new Object[]{jTextField5.getText(),jTextField6.getText(),jTextField7.getText(),jTextField8.getText()});   

            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            
            //pst.close();
               //con.close();
        
      }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,"No duplicate values allowed");
        }       
catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null,"It must contain number only");
        }             // TODO add your h  // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       try{
            DefaultTableModel model=(DefaultTableModel)jTable4.getModel();
           
            System.out.println("Add");
            int enrol=Integer.parseInt(jTextField10.getText());
            System.out.println(enrol);
            String name=jTextField11.getText();
            System.out.println(name);
            String batch=(String)jComboBox1.getSelectedItem();
            System.out.println(batch);
            String pc_no=(String)jComboBox2.getSelectedItem();
            System.out.println(pc_no);
            String year=(String)jComboBox3.getSelectedItem();
            String yoa=jTextField9.getText();
            int y1=Integer.parseInt(yoa);
             if(!isStringOnlyAlphabet(jTextField11.getText()))
   JOptionPane.showMessageDialog(null,"Only allowed Alphabets "); 
             else if(jTextField10.getText().length()<6)
                 JOptionPane.showMessageDialog(null," Enrollment must be number and 6 digits long");
              else if(jTextField9.getText().length()<4)
                 JOptionPane.showMessageDialog(null,"Year of Admission must be number and 4 digits long");
             else
              {
               
            String q="insert into master1 values(?,?,?,?,?,?)";
            System.out.println("PrepareStatement");
            pst4=con.prepareStatement(q);

            pst4.setInt(1,enrol);
            pst4.setString(2,name);
            pst4.setString(3,batch);
            pst4.setString(4,year);
            pst4.setString(5,pc_no);
            pst4.setString(6,yoa);
           
            pst4.execute();
             model.addRow(new Object[]{jTextField10.getText(),jTextField11.getText(),jComboBox1.getSelectedItem(),jComboBox3.getSelectedItem(),jComboBox2.getSelectedItem(),jTextField9.getText()}); 

            jTextField10.setText("");
            jTextField11.setText("");
            
            //pst.close();
            //con.close();
              }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,"No duplicate values allowed");
        }    // TODO add your handling code here:
       catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this,"Must be a number");
        }   
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        int row = jTable4.getSelectedRow();
        if(row<0) 
        {
            JOptionPane.showMessageDialog(this,  "Select specific row to update/delete"); 
        }
        else
        {
        String eve = (String)jTable4.getModel().getValueAt(row, 0).toString();
        String delRow = "delete from master1 where enrollment="+eve;
        try {
            pst = con.prepareStatement(delRow);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Deleted selected row successfully!!!!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,  e.getMessage());
        }
        model.removeRow(row);  
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
Enroll e=new Enroll();
this.setVisible(true);
e.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
Subject s=new Subject();
this.setVisible(true);
s.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
Date d=new Date();
this.setVisible(true);
d.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
this.setState(JFrame.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
 System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
try{
            DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
         
            System.out.println("Add");
            String id=jTextField1.getText();
            int i=Integer.parseInt(id);
                   
            System.out.println(id);
            String name=jTextField2.getText();
            System.out.println(name);
            String password=jTextField3.getText();
            System.out.println(password);
            String subject=jTextField4.getText();
            System.out.println(subject);
            String hint=jTextField12.getText();
            System.out.println(hint);
           
            if(!isStringOnlyAlphabet(jTextField2.getText())&&!isStringOnlyAlphabet(jTextField4.getText()))
   JOptionPane.showMessageDialog(null,"Only allowed Alphabets "); 
            else if(!isStringOnlyAlphabet(jTextField12.getText()))
                JOptionPane.showMessageDialog(null,"Only allowed Alphabets "); 
            else if(!isValid(jTextField3.getText()))
               JOptionPane.showMessageDialog(null,"Must contain alphabets and numbers "); 
            else if(jTextField1.getText().length()<4)
               JOptionPane.showMessageDialog(null,"Must contain only numbers and should be 4 digits long ");  
            
                
            
            
           else
            {model.addRow(new Object[]{jTextField1.getText(),jTextField2.getText(),jTextField3.getText(),jTextField4.getText(),jTextField12.getText()});
            String q="insert into staff(staff_id,name,password,subject,hint_answer) values(?,?,?,?,?)";
            System.out.println("PrepareStatement");
            pst=con.prepareStatement(q);

            pst.setString(1,id);
            pst.setString(2,name);
            pst.setString(3,password);
            pst.setString(4,subject);
            pst.setString(5,hint);
           
            pst.execute();

            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField12.setText("");
            //pst.close();
            //con.close();
            }
        
}
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,e);
        } 
catch(NumberFormatException e)
{
    
   JOptionPane.showMessageDialog(null,"It should be a number and must be 4 digits long");
}
// TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int row = jTable2.getSelectedRow();
        if(row<0) 
        {
            JOptionPane.showMessageDialog(this,  "Select specific row to delete"); 
        }
        else
        {
        String eve = (String)jTable2.getModel().getValueAt(row, 0).toString();
        String delRow = "delete from staff where STAFF_ID="+eve;
        System.out.println("Deleted");
        try {
            pst1 = con.prepareStatement(delRow);
            pst1.execute();
            JOptionPane.showMessageDialog(this, "Deleted selected row successfully!!!!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,  e.getMessage());
        }
        model.removeRow(row);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
Yoa y=new Yoa();
y.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        int row = jTable4.getSelectedRow();
        if(row<0) 
        {
            JOptionPane.showMessageDialog(this,  "Select specific row to delete or update"); 
        } 
        else
        {
            
           
           
       
      
              try
              {
              PreparedStatement pst=con.prepareStatement("update master1 set Name=? where enrollment=?");
             PreparedStatement pst1=con.prepareStatement("update master1 set Batch=? where enrollment=?");
             PreparedStatement pst2=con.prepareStatement("update master1 set Year=? where enrollment=?");
             PreparedStatement pst3=con.prepareStatement("update master1 set Pc=? where enrollment=?");
             PreparedStatement pst4=con.prepareStatement("update master1 set yoa=? where enrollment=?");
             
              pst.setString(1,jTextField11.getText());
              pst1.setString(1,(String)jComboBox1.getSelectedItem());
              pst2.setString(1,(String)jComboBox3.getSelectedItem());
              pst3.setString(1,(String)jComboBox2.getSelectedItem());
               pst4.setString(1,jTextField9.getText());
               pst.setString(2,jTextField10.getText());
               pst1.setString(2,jTextField10.getText());
               pst2.setString(2,jTextField10.getText());
               pst3.setString(2,jTextField10.getText());
               pst4.setString(2,jTextField10.getText());
               pst.execute();
                pst1.execute();
                 pst2.execute();
                  pst3.execute();
                  pst4.execute();
               model.setValueAt(jTextField10.getText(), row, 0);
            model.setValueAt(jTextField11.getText(), row, 1);
            model.setValueAt(jTextField9.getText(), row, 5);
             model.setValueAt(jComboBox1.getSelectedItem(), row, 2);
              model.setValueAt(jComboBox3.getSelectedItem(), row, 3);
               model.setValueAt(jComboBox2.getSelectedItem(), row, 4);
              
              }
              catch(SQLException s)
              {
                  System.out.println(s);
              }
              
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
     int selectedRow = jTable4.getSelectedRow();
    
        DefaultTableModel model = (DefaultTableModel)jTable4.getModel();
        jTextField10.setText(model.getValueAt(selectedRow, 0).toString());
        jTextField11.setText(model.getValueAt(selectedRow, 1).toString());
        jTextField9.setText(model.getValueAt(selectedRow, 5).toString());
     // TODO add your handling code here:
    }//GEN-LAST:event_jTable4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPan().setVisible(true);
            }
        });
    }
private void setIcon() {
      setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon1.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
