/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Myproject;

import java.awt.BorderLayout;
import java.sql.DriverManager;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;

import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sansk
 */
public class StaffLogin extends javax.swing.JFrame {

String n;
    Connection con;
public static String subj;    
    ResultSet rs,rs1,rs2,rs3;
    
    public StaffLogin(String sub) {
        setIcon();
        initComponents();
        subj=sub;
      try{
      con=DriverManager.getConnection("jdbc:mysql://localhost:3306/information?serverTimezone=IST","root","");
      System.out.println("connect");
   // n=subject[0];
        //Getset g=new Getset();
       // String sub=g.getSubject();
        PreparedStatement s=con.prepareStatement("select Enrollment,sdate,login,logout,Total_time,OTP,attendance from stud_info where Subject=?");
        s.setString(1, sub);
        rs=s.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        PreparedStatement s1=con.prepareStatement("select Enrollment,PC,sdate from stud_info where Subject=?");
        s1.setString(1, sub);
        rs3=s1.executeQuery();
        jTable2.setModel(DbUtils.resultSetToTableModel(rs3));
        Statement st=con.createStatement();
        rs1=st.executeQuery("select Enrollment from master1");
        while(rs1.next())
        {
            jComboBox1.addItem(rs1.getString("Enrollment"));
        }
        /*rs2=st.executeQuery("select sdate from stud_info");
        while(rs2.next())
        {
            jComboBox2.addItem(rs2.getString("sdate"));
        }*/
        
      }
      catch(SQLException e)
      {
          System.out.println(e);
      }
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jTabbedPane1.setForeground(new java.awt.Color(102, 102, 255));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jPanel1.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("ENROLLMENT:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 110, 170, 51);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(180, 120, 146, 39);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 153));
        jButton1.setText("ADD");
        jPanel1.add(jButton1);
        jButton1.setBounds(130, 240, 136, 48);

        jButton2.setBackground(new java.awt.Color(153, 255, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("PRESENT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 330, 150, 50);
        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(500, 360, 2, 2);

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("ABSENT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(210, 330, 140, 50);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable1.setBackground(new java.awt.Color(153, 153, 255));
        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(153, 153, 255));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        jScrollPane4.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(420, 80, 580, 490);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*FOR UPDATED RECORDS KINDLY RESTART THE APPLICATION!!");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 610, 700, 22);

        jTabbedPane1.addTab("ATTENDANCE", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enrollment", "Pc_no", "date"
            }
        ));
        jTable2.setRowHeight(30
        );
        jScrollPane3.setViewportView(jTable2);

        jScrollPane5.setViewportView(jScrollPane3);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 869, 579));

        jTabbedPane1.addTab("COMPUTER USED", jPanel2);

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JAN", "FEB", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("CHOOSE A MONTH FOR REPORT:");

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 153));
        jButton4.setText("GENERATE REPORT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(371, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(166, 166, 166)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("STUDENT ATTENDANCE REPORT", jPanel3);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 153));
        jButton5.setText("LOGOUT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("LOGOUT", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Smart Lab Assistant");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 17, 520, 70));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("-");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 30, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        if(row<0) 
        {
            JOptionPane.showMessageDialog(this,  "Select specific row you want to mark present"); 
        }
        else
        {
        String p=jButton2.getActionCommand();
        System.out.println(p);
        model.setValueAt(p, row, 5);
         
        try{
            Statement pt=con.createStatement();
            pt.executeUpdate("update stud_info set attendance='"+p+"'");
        }
        catch(SQLException e)
        {
         System.out.print(e);   
        }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        if(row<0) 
        {
            JOptionPane.showMessageDialog(this,  "Select specific row you want to mark as absent"); 
        }
        else
        {
        String p=jButton3.getActionCommand();
        model.setValueAt(p, row, 5);
         
        try{
            Statement pt=con.createStatement();
            pt.executeUpdate("update stud_info set attendance='"+p+"'");
        }
        catch(SQLException e)
        {
         System.out.print(e);   
        }
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JOptionPane.showMessageDialog(this,  "Report generated at"+FileSystemView.getFileSystemView().getDefaultDirectory().getPath()); 
        try{                                         
            String month=(String)jComboBox2.getSelectedItem();
            switch(month)
            {case "JAN":
                PreparedStatement s2=con.prepareStatement("select Enrollment,Subject,sdate,attendance from stud_info where MONTHNAME(sdate)=?order by sdate DESC");
                s2.setString(1, "JANUARY");
                rs=s2.executeQuery();
                Document my_pdf_report1 = new Document();
                PdfWriter.getInstance(my_pdf_report1, new FileOutputStream(FileSystemView.getFileSystemView().getDefaultDirectory().getPath()+"\\Attendance Report of "+month+".pdf"));
                my_pdf_report1.open();    
                 Paragraph centerAlignedParagraph1= new Paragraph("Student Attendance Report");
                  centerAlignedParagraph1.setAlignment(Element.ALIGN_CENTER);
                my_pdf_report1.add(new Paragraph(centerAlignedParagraph1));
                my_pdf_report1.add( Chunk.NEWLINE );
                //we have four columns in our table
                PdfPTable my_report_table1 = new PdfPTable(4);
                //create a cell object
                PdfPCell table_cell1;
               
                while (rs.next()) {      
                     String en1 ="Enrollment";
                                table_cell1=new PdfPCell(new Phrase(en1));
                                my_report_table1.addCell(table_cell1);
                                String s1 ="Subject";
                                table_cell1=new PdfPCell(new Phrase(s1));
                                my_report_table1.addCell(table_cell1);
                                String d1 ="Date";
                                table_cell1=new PdfPCell(new Phrase(d1));
                                my_report_table1.addCell(table_cell1);
                                String a1 ="Attendance";
                                table_cell1=new PdfPCell(new Phrase(a1));
                                my_report_table1.addCell(table_cell1);
                                String enrollment = rs.getString("Enrollment");
                                table_cell1=new PdfPCell(new Phrase(enrollment));
                                my_report_table1.addCell(table_cell1);
                                String subject=rs.getString("Subject");
                                table_cell1=new PdfPCell(new Phrase(subject));
                                my_report_table1.addCell(table_cell1);
                                String sdate=rs.getString("sdate");
                                table_cell1=new PdfPCell(new Phrase(sdate));
                                my_report_table1.addCell(table_cell1);
                                String attendance=rs.getString("attendance");
                                table_cell1=new PdfPCell(new Phrase(attendance));
                                my_report_table1.addCell(table_cell1);
                                }
                /* Attach report table to PDF */
                my_pdf_report1.add(my_report_table1);                       
                my_pdf_report1.close();
                break;
                        // pt.executeUpdate();
                case "FEB":
                PreparedStatement s3=con.prepareStatement("select Enrollment,Subject,sdate,attendance from stud_info where MONTHNAME(sdate)=?order by sdate DESC");
                s3.setString(1, "FEBRUARY");
                rs=s3.executeQuery();
                Document my_pdf_report2 = new Document();
                PdfWriter.getInstance(my_pdf_report2, new FileOutputStream(FileSystemView.getFileSystemView().getDefaultDirectory().getPath()+"\\Attendance Report of "+month+".pdf"));
                my_pdf_report2.open();    
                 Paragraph centerAlignedParagraph2= new Paragraph("Student Attendance Report");
                  centerAlignedParagraph2.setAlignment(Element.ALIGN_CENTER);
                my_pdf_report2.add(new Paragraph(centerAlignedParagraph2));
                my_pdf_report2.add( Chunk.NEWLINE );
                //we have four columns in our table
                PdfPTable my_report_table2 = new PdfPTable(4);
                //create a cell object
                PdfPCell table_cell2;
               
                while (rs.next()) {      
                     String en1 ="Enrollment";
                                table_cell2=new PdfPCell(new Phrase(en1));
                                my_report_table2.addCell(table_cell2);
                                String s1 ="Subject";
                                table_cell2=new PdfPCell(new Phrase(s1));
                                my_report_table2.addCell(table_cell2);
                                String d1 ="Date";
                                table_cell2=new PdfPCell(new Phrase(d1));
                                my_report_table2.addCell(table_cell2);
                                String a1 ="Attendance";
                                table_cell2=new PdfPCell(new Phrase(a1));
                                my_report_table2.addCell(table_cell2);
                                String enrollment = rs.getString("Enrollment");
                                table_cell2=new PdfPCell(new Phrase(enrollment));
                                my_report_table2.addCell(table_cell2);
                                String subject=rs.getString("Subject");
                                table_cell2=new PdfPCell(new Phrase(subject));
                                my_report_table2.addCell(table_cell2);
                                String sdate=rs.getString("sdate");
                                table_cell2=new PdfPCell(new Phrase(sdate));
                                my_report_table2.addCell(table_cell2);
                                String attendance=rs.getString("attendance");
                                table_cell2=new PdfPCell(new Phrase(attendance));
                                my_report_table2.addCell(table_cell2);
                                }
                /* Attach report table to PDF */
                my_pdf_report2.add(my_report_table2);                       
                my_pdf_report2.close();
                break;
                        // pt.executeUpdate();
                case "APRIL":
                PreparedStatement s4=con.prepareStatement("select Enrollment,Subject,sdate,attendance from stud_info where MONTHNAME(sdate)=?order by sdate DESC");
                s4.setString(1, "APRIL");
                rs=s4.executeQuery();
                Document my_pdf_report3 = new Document();
                PdfWriter.getInstance(my_pdf_report3, new FileOutputStream(FileSystemView.getFileSystemView().getDefaultDirectory().getPath()+"\\Attendance Report of "+month+".pdf"));
                my_pdf_report3.open();    
                 Paragraph centerAlignedParagraph3= new Paragraph("Student Attendance Report");
                  centerAlignedParagraph3.setAlignment(Element.ALIGN_CENTER);
                my_pdf_report3.add(new Paragraph(centerAlignedParagraph3));
                my_pdf_report3.add( Chunk.NEWLINE );
                //we have four columns in our table
                PdfPTable my_report_table3 = new PdfPTable(4);
                //create a cell object
                PdfPCell table_cell3;
               
                while (rs.next()) {      
                     String en1 ="Enrollment";
                                table_cell3=new PdfPCell(new Phrase(en1));
                                my_report_table3.addCell(table_cell3);
                                String s1 ="Subject";
                                table_cell3=new PdfPCell(new Phrase(s1));
                                my_report_table3.addCell(table_cell3);
                                String d1 ="Date";
                                table_cell3=new PdfPCell(new Phrase(d1));
                                my_report_table3.addCell(table_cell3);
                                String a1 ="Attendance";
                                table_cell3=new PdfPCell(new Phrase(a1));
                                my_report_table3.addCell(table_cell3);
                                String enrollment = rs.getString("Enrollment");
                                table_cell3=new PdfPCell(new Phrase(enrollment));
                                my_report_table3.addCell(table_cell3);
                                String subject=rs.getString("Subject");
                                table_cell3=new PdfPCell(new Phrase(subject));
                                my_report_table3.addCell(table_cell3);
                                String sdate=rs.getString("sdate");
                                table_cell3=new PdfPCell(new Phrase(sdate));
                                my_report_table3.addCell(table_cell3);
                                String attendance=rs.getString("attendance");
                                table_cell3=new PdfPCell(new Phrase(attendance));
                                my_report_table3.addCell(table_cell3);
                                }
                /* Attach report table to PDF */
                my_pdf_report3.add(my_report_table3);                       
                my_pdf_report3.close();
                break;
                        // pt.executeUpdate();
                        
            case "MAY":
                PreparedStatement s5=con.prepareStatement("select Enrollment,Subject,sdate,attendance from stud_info where MONTHNAME(sdate)=?order by sdate DESC");
                s5.setString(1, "MAY");
                rs=s5.executeQuery();
                Document my_pdf_report5 = new Document();
                PdfWriter.getInstance(my_pdf_report5, new FileOutputStream(FileSystemView.getFileSystemView().getDefaultDirectory().getPath()+"\\Attendance Report of "+month+".pdf"));
                my_pdf_report5.open();    
                 Paragraph centerAlignedParagraph5= new Paragraph("Student Attendance Report");
                  centerAlignedParagraph5.setAlignment(Element.ALIGN_CENTER);
                my_pdf_report5.add(new Paragraph(centerAlignedParagraph5));
                my_pdf_report5.add( Chunk.NEWLINE );
                //we have four columns in our table
                PdfPTable my_report_table5 = new PdfPTable(4);
                //create a cell object
                PdfPCell table_cell5;
               
                while (rs.next()) {      
                     String en1 ="Enrollment";
                                table_cell5=new PdfPCell(new Phrase(en1));
                                my_report_table5.addCell(table_cell5);
                                String s1 ="Subject";
                                table_cell5=new PdfPCell(new Phrase(s1));
                                my_report_table5.addCell(table_cell5);
                                String d1 ="Date";
                                table_cell5=new PdfPCell(new Phrase(d1));
                                my_report_table5.addCell(table_cell5);
                                String a1 ="Attendance";
                                table_cell5=new PdfPCell(new Phrase(a1));
                                my_report_table5.addCell(table_cell5);
                                String enrollment = rs.getString("Enrollment");
                                table_cell5=new PdfPCell(new Phrase(enrollment));
                                my_report_table5.addCell(table_cell5);
                                String subject=rs.getString("Subject");
                                table_cell5=new PdfPCell(new Phrase(subject));
                                my_report_table5.addCell(table_cell5);
                                String sdate=rs.getString("sdate");
                                table_cell5=new PdfPCell(new Phrase(sdate));
                                my_report_table5.addCell(table_cell5);
                                String attendance=rs.getString("attendance");
                                table_cell5=new PdfPCell(new Phrase(attendance));
                                my_report_table5.addCell(table_cell5);
                                }
                /* Attach report table to PDF */
                my_pdf_report5.add(my_report_table5);                       
                my_pdf_report5.close();
                break;
                        // pt.executeUpdate();
            case "JUNE":
                PreparedStatement s6=con.prepareStatement("select Enrollment,Subject,sdate,attendance from stud_info where MONTHNAME(sdate)=?order by sdate DESC");
                s6.setString(1, "JUNE");
                rs=s6.executeQuery();
                Document my_pdf_report6 = new Document();
                PdfWriter.getInstance(my_pdf_report6, new FileOutputStream(FileSystemView.getFileSystemView().getDefaultDirectory().getPath()+"\\Attendance Report of "+month+".pdf"));
                my_pdf_report6.open();    
                 Paragraph centerAlignedParagraph6= new Paragraph("Student Attendance Report");
                  centerAlignedParagraph6.setAlignment(Element.ALIGN_CENTER);
                my_pdf_report6.add(new Paragraph(centerAlignedParagraph6));
                my_pdf_report6.add( Chunk.NEWLINE );
                //we have four columns in our table
                PdfPTable my_report_table6 = new PdfPTable(4);
                //create a cell object
                PdfPCell table_cell6;
               
                while (rs.next()) {      
                     String en1 ="Enrollment";
                                table_cell6=new PdfPCell(new Phrase(en1));
                                my_report_table6.addCell(table_cell6);
                                String s1 ="Subject";
                                table_cell1=new PdfPCell(new Phrase(s1));
                                my_report_table6.addCell(table_cell6);
                                String d1 ="Date";
                                table_cell6=new PdfPCell(new Phrase(d1));
                                my_report_table6.addCell(table_cell6);
                                String a1 ="Attendance";
                                table_cell6=new PdfPCell(new Phrase(a1));
                                my_report_table6.addCell(table_cell6);
                                String enrollment = rs.getString("Enrollment");
                                table_cell6=new PdfPCell(new Phrase(enrollment));
                                my_report_table6.addCell(table_cell6);
                                String subject=rs.getString("Subject");
                                table_cell6=new PdfPCell(new Phrase(subject));
                                my_report_table6.addCell(table_cell6);
                                String sdate=rs.getString("sdate");
                                table_cell6=new PdfPCell(new Phrase(sdate));
                                my_report_table6.addCell(table_cell1);
                                String attendance=rs.getString("attendance");
                                table_cell6=new PdfPCell(new Phrase(attendance));
                                my_report_table6.addCell(table_cell6);
                                }
                /* Attach report table to PDF */
                my_pdf_report6.add(my_report_table6);                       
                my_pdf_report6.close();
                break;
                        // pt.executeUpdate();
                case "AUGUST":
                PreparedStatement s7=con.prepareStatement("select Enrollment,Subject,sdate,attendance from stud_info where MONTHNAME(sdate)=?order by sdate DESC");
                s7.setString(1, "AUGUST");
                rs=s7.executeQuery();
                Document my_pdf_report7 = new Document();
                PdfWriter.getInstance(my_pdf_report7, new FileOutputStream(FileSystemView.getFileSystemView().getDefaultDirectory().getPath()+"\\Attendance Report of "+month+".pdf"));
                my_pdf_report7.open();    
                 Paragraph centerAlignedParagraph7= new Paragraph("Student Attendance Report");
                  centerAlignedParagraph7.setAlignment(Element.ALIGN_CENTER);
                my_pdf_report7.add(new Paragraph(centerAlignedParagraph7));
                my_pdf_report7.add( Chunk.NEWLINE );
                //we have four columns in our table
                PdfPTable my_report_table7 = new PdfPTable(4);
                //create a cell object
                PdfPCell table_cell7;
               
                while (rs.next()) {      
                     String en1 ="Enrollment";
                                table_cell7=new PdfPCell(new Phrase(en1));
                                my_report_table7.addCell(table_cell7);
                                String s1 ="Subject";
                                table_cell7=new PdfPCell(new Phrase(s1));
                                my_report_table7.addCell(table_cell7);
                                String d1 ="Date";
                                table_cell7=new PdfPCell(new Phrase(d1));
                                my_report_table7.addCell(table_cell7);
                                String a1 ="Attendance";
                                table_cell7=new PdfPCell(new Phrase(a1));
                                my_report_table7.addCell(table_cell7);
                                String enrollment = rs.getString("Enrollment");
                                table_cell7=new PdfPCell(new Phrase(enrollment));
                                my_report_table7.addCell(table_cell7);
                                String subject=rs.getString("Subject");
                                table_cell7=new PdfPCell(new Phrase(subject));
                                my_report_table7.addCell(table_cell7);
                                String sdate=rs.getString("sdate");
                                table_cell7=new PdfPCell(new Phrase(sdate));
                                my_report_table7.addCell(table_cell7);
                                String attendance=rs.getString("attendance");
                                table_cell7=new PdfPCell(new Phrase(attendance));
                                my_report_table7.addCell(table_cell7);
                                }
                /* Attach report table to PDF */
                my_pdf_report7.add(my_report_table7);                       
                my_pdf_report7.close();
                break;
                        // pt.executeUpdate();
                case "SEPTEMBER":
                PreparedStatement s8=con.prepareStatement("select Enrollment,Subject,sdate,attendance from stud_info where MONTHNAME(sdate)=?order by sdate DESC");
                s8.setString(1, "SEPTEMBER");
                rs=s8.executeQuery();
                Document my_pdf_report8 = new Document();
                PdfWriter.getInstance(my_pdf_report8, new FileOutputStream(FileSystemView.getFileSystemView().getDefaultDirectory().getPath()+"\\Attendance Report of "+month+".pdf"));
                my_pdf_report8.open();    
                 Paragraph centerAlignedParagraph8= new Paragraph("Student Attendance Report");
                  centerAlignedParagraph8.setAlignment(Element.ALIGN_CENTER);
                my_pdf_report8.add(new Paragraph(centerAlignedParagraph8));
                my_pdf_report8.add( Chunk.NEWLINE );
                //we have four columns in our table
                PdfPTable my_report_table8 = new PdfPTable(4);
                //create a cell object
                PdfPCell table_cell8;
               
                while (rs.next()) {      
                     String en1 ="Enrollment";
                                table_cell8=new PdfPCell(new Phrase(en1));
                                my_report_table8.addCell(table_cell8);
                                String s1 ="Subject";
                                table_cell8=new PdfPCell(new Phrase(s1));
                                my_report_table8.addCell(table_cell8);
                                String d1 ="Date";
                                table_cell8=new PdfPCell(new Phrase(d1));
                                my_report_table8.addCell(table_cell8);
                                String a1 ="Attendance";
                                table_cell8=new PdfPCell(new Phrase(a1));
                                my_report_table8.addCell(table_cell8);
                                String enrollment = rs.getString("Enrollment");
                                table_cell8=new PdfPCell(new Phrase(enrollment));
                                my_report_table8.addCell(table_cell8);
                                String subject=rs.getString("Subject");
                                table_cell8=new PdfPCell(new Phrase(subject));
                                my_report_table8.addCell(table_cell8);
                                String sdate=rs.getString("sdate");
                                table_cell8=new PdfPCell(new Phrase(sdate));
                                my_report_table8.addCell(table_cell8);
                                String attendance=rs.getString("attendance");
                                table_cell8=new PdfPCell(new Phrase(attendance));
                                my_report_table8.addCell(table_cell8);
                                }
                /* Attach report table to PDF */
                my_pdf_report8.add(my_report_table8);                       
                my_pdf_report8.close();
                break;
                        // pt.executeUpdate();
                case "OCTOBER":
                PreparedStatement s9=con.prepareStatement("select Enrollment,Subject,sdate,attendance from stud_info where MONTHNAME(sdate)=?order by sdate DESC");
                s9.setString(1, "OCTOBER");
                rs=s9.executeQuery();
                Document my_pdf_report9 = new Document();
                PdfWriter.getInstance(my_pdf_report9, new FileOutputStream(FileSystemView.getFileSystemView().getDefaultDirectory().getPath()+"\\Attendance Report of "+month+".pdf"));
                my_pdf_report9.open();    
                 Paragraph centerAlignedParagraph9= new Paragraph("Student Attendance Report");
                  centerAlignedParagraph9.setAlignment(Element.ALIGN_CENTER);
                my_pdf_report9.add(new Paragraph(centerAlignedParagraph9));
                my_pdf_report9.add( Chunk.NEWLINE );
                //we have four columns in our table
                PdfPTable my_report_table9 = new PdfPTable(4);
                //create a cell object
                PdfPCell table_cell9;
               
                while (rs.next()) {      
                     String en1 ="Enrollment";
                                table_cell9=new PdfPCell(new Phrase(en1));
                                my_report_table9.addCell(table_cell9);
                                String s1 ="Subject";
                                table_cell9=new PdfPCell(new Phrase(s1));
                                my_report_table9.addCell(table_cell9);
                                String d1 ="Date";
                                table_cell9=new PdfPCell(new Phrase(d1));
                                my_report_table9.addCell(table_cell9);
                                String a1 ="Attendance";
                                table_cell9=new PdfPCell(new Phrase(a1));
                                my_report_table9.addCell(table_cell9);
                                String enrollment = rs.getString("Enrollment");
                                table_cell9=new PdfPCell(new Phrase(enrollment));
                                my_report_table9.addCell(table_cell9);
                                String subject=rs.getString("Subject");
                                table_cell9=new PdfPCell(new Phrase(subject));
                                my_report_table9.addCell(table_cell9);
                                String sdate=rs.getString("sdate");
                                table_cell9=new PdfPCell(new Phrase(sdate));
                                my_report_table9.addCell(table_cell9);
                                String attendance=rs.getString("attendance");
                                table_cell9=new PdfPCell(new Phrase(attendance));
                                my_report_table9.addCell(table_cell9);
                                }
                /* Attach report table to PDF */
                my_pdf_report9.add(my_report_table9);                       
                my_pdf_report9.close();
                break;
                        // pt.executeUpdate();
                case "NOVEMBER":
                PreparedStatement s10=con.prepareStatement("select Enrollment,Subject,sdate,attendance from stud_info where MONTHNAME(sdate)=?order by sdate DESC");
                s10.setString(1, "NOVEMBER");
                rs=s10.executeQuery();
                Document my_pdf_report10 = new Document();
                PdfWriter.getInstance(my_pdf_report10, new FileOutputStream(FileSystemView.getFileSystemView().getDefaultDirectory().getPath()+"\\Attendance Report of "+month+".pdf"));
                my_pdf_report10.open();    
                 Paragraph centerAlignedParagraph10= new Paragraph("Student Attendance Report");
                  centerAlignedParagraph10.setAlignment(Element.ALIGN_CENTER);
                my_pdf_report10.add(new Paragraph(centerAlignedParagraph10));
                my_pdf_report10.add( Chunk.NEWLINE );
                //we have four columns in our table
                PdfPTable my_report_table10 = new PdfPTable(4);
                //create a cell object
                PdfPCell table_cell10;
               
                while (rs.next()) {      
                     String en1 ="Enrollment";
                                table_cell10=new PdfPCell(new Phrase(en1));
                                my_report_table10.addCell(table_cell10);
                                String s1 ="Subject";
                                table_cell10=new PdfPCell(new Phrase(s1));
                                my_report_table10.addCell(table_cell10);
                                String d1 ="Date";
                                table_cell10=new PdfPCell(new Phrase(d1));
                                my_report_table10.addCell(table_cell10);
                                String a1 ="Attendance";
                                table_cell10=new PdfPCell(new Phrase(a1));
                                my_report_table10.addCell(table_cell10);
                                String enrollment = rs.getString("Enrollment");
                                table_cell10=new PdfPCell(new Phrase(enrollment));
                                my_report_table10.addCell(table_cell10);
                                String subject=rs.getString("Subject");
                                table_cell10=new PdfPCell(new Phrase(subject));
                                my_report_table10.addCell(table_cell10);
                                String sdate=rs.getString("sdate");
                                table_cell10=new PdfPCell(new Phrase(sdate));
                                my_report_table10.addCell(table_cell10);
                                String attendance=rs.getString("attendance");
                                table_cell10=new PdfPCell(new Phrase(attendance));
                                my_report_table10.addCell(table_cell10);
                                }
                /* Attach report table to PDF */
                my_pdf_report10.add(my_report_table10);                       
                my_pdf_report10.close();
                break;
                        // pt.executeUpdate();
                case "DECEMBER":
                PreparedStatement s11=con.prepareStatement("select Enrollment,Subject,sdate,attendance from stud_info where MONTHNAME(sdate)=?order by sdate DESC");
                s11.setString(1, "DECEMBER");
                rs=s11.executeQuery();
                Document my_pdf_report11 = new Document();
                PdfWriter.getInstance(my_pdf_report11, new FileOutputStream(FileSystemView.getFileSystemView().getDefaultDirectory().getPath()+"\\Attendance Report of "+month+".pdf"));
                my_pdf_report11.open();    
                 Paragraph centerAlignedParagraph11= new Paragraph("Student Attendance Report");
                  centerAlignedParagraph11.setAlignment(Element.ALIGN_CENTER);
                my_pdf_report11.add(new Paragraph(centerAlignedParagraph11));
                my_pdf_report11.add( Chunk.NEWLINE );
                //we have four columns in our table
                PdfPTable my_report_table11 = new PdfPTable(4);
                //create a cell object
                PdfPCell table_cell11;
               
                while (rs.next()) {      
                     String en1 ="Enrollment";
                                table_cell11=new PdfPCell(new Phrase(en1));
                                my_report_table11.addCell(table_cell11);
                                String s1 ="Subject";
                                table_cell11=new PdfPCell(new Phrase(s1));
                                my_report_table11.addCell(table_cell11);
                                String d1 ="Date";
                                table_cell11=new PdfPCell(new Phrase(d1));
                                my_report_table11.addCell(table_cell11);
                                String a1 ="Attendance";
                                table_cell11=new PdfPCell(new Phrase(a1));
                                my_report_table11.addCell(table_cell11);
                                String enrollment = rs.getString("Enrollment");
                                table_cell11=new PdfPCell(new Phrase(enrollment));
                                my_report_table11.addCell(table_cell11);
                                String subject=rs.getString("Subject");
                                table_cell11=new PdfPCell(new Phrase(subject));
                                my_report_table11.addCell(table_cell11);
                                String sdate=rs.getString("sdate");
                                table_cell11=new PdfPCell(new Phrase(sdate));
                                my_report_table11.addCell(table_cell11);
                                String attendance=rs.getString("attendance");
                                table_cell11=new PdfPCell(new Phrase(attendance));
                                my_report_table11.addCell(table_cell11);
                                }
                /* Attach report table to PDF */
                my_pdf_report11.add(my_report_table11);                       
                my_pdf_report11.close();
                break;
                        // pt.executeUpdate();
                case "JULY":
                PreparedStatement s12=con.prepareStatement("select Enrollment,Subject,sdate,attendance from stud_info where MONTHNAME(sdate)=? order by sdate DESC");
                s12.setString(1, "JULY");
                rs=s12.executeQuery();
                Document my_pdf_report12 = new Document();
                PdfWriter.getInstance(my_pdf_report12, new FileOutputStream(FileSystemView.getFileSystemView().getDefaultDirectory().getPath()+"\\Attendance Report of "+month+".pdf"));
                my_pdf_report12.open();    
                 Paragraph centerAlignedParagraph12= new Paragraph("Student Attendance Report");
                  centerAlignedParagraph12.setAlignment(Element.ALIGN_CENTER);
                my_pdf_report12.add(new Paragraph(centerAlignedParagraph12));
                my_pdf_report12.add( Chunk.NEWLINE );
                //we have four columns in our table
                PdfPTable my_report_table12 = new PdfPTable(4);
                //create a cell object
                PdfPCell table_cell12;
               
                while (rs.next()) {      
                     String en1 ="Enrollment";
                                table_cell12=new PdfPCell(new Phrase(en1));
                                my_report_table12.addCell(table_cell12);
                                String s1 ="Subject";
                                table_cell12=new PdfPCell(new Phrase(s1));
                                my_report_table12.addCell(table_cell12);
                                String d1 ="Date";
                                table_cell12=new PdfPCell(new Phrase(d1));
                                my_report_table12.addCell(table_cell12);
                                String a1 ="Attendance";
                                table_cell12=new PdfPCell(new Phrase(a1));
                                my_report_table12.addCell(table_cell12);
                                String enrollment = rs.getString("Enrollment");
                                table_cell12=new PdfPCell(new Phrase(enrollment));
                                my_report_table12.addCell(table_cell12);
                                String subject=rs.getString("Subject");
                                table_cell12=new PdfPCell(new Phrase(subject));
                                my_report_table12.addCell(table_cell12);
                                String sdate=rs.getString("sdate");
                                table_cell12=new PdfPCell(new Phrase(sdate));
                                my_report_table12.addCell(table_cell12);
                                String attendance=rs.getString("attendance");
                                table_cell12=new PdfPCell(new Phrase(attendance));
                                my_report_table12.addCell(table_cell12);
                                }
                /* Attach report table to PDF */
                my_pdf_report12.add(my_report_table12);                       
                my_pdf_report12.close();
                break;
                        // pt.executeUpdate();
                case "MARCH":
                PreparedStatement s=con.prepareStatement("select Enrollment,Subject,sdate,attendance from stud_info where MONTHNAME(sdate)=?order by sdate DESC");
                s.setString(1, "MARCH");
                rs=s.executeQuery();
                Document my_pdf_report = new Document();
                PdfWriter.getInstance(my_pdf_report, new FileOutputStream(FileSystemView.getFileSystemView().getDefaultDirectory().getPath()+"\\Attendance Report of "+month+".pdf"));
                my_pdf_report.open();    
                 Paragraph centerAlignedParagraph= new Paragraph("Student Attendance Report");
                  centerAlignedParagraph.setAlignment(Element.ALIGN_CENTER);
                my_pdf_report.add(new Paragraph(centerAlignedParagraph));
                my_pdf_report.add( Chunk.NEWLINE );
                //we have four columns in our table
                PdfPTable my_report_table = new PdfPTable(4);
                //create a cell object
                PdfPCell table_cell;
               
                while (rs.next()) {      
                     String en1 ="Enrollment";
                                table_cell=new PdfPCell(new Phrase(en1));
                                my_report_table.addCell(table_cell);
                                String s1 ="Subject";
                                table_cell=new PdfPCell(new Phrase(s1));
                                my_report_table.addCell(table_cell);
                                String d1 ="Date";
                                table_cell=new PdfPCell(new Phrase(d1));
                                my_report_table.addCell(table_cell);
                                String a1 ="Attendance";
                                table_cell=new PdfPCell(new Phrase(a1));
                                my_report_table.addCell(table_cell);
                                String enrollment = rs.getString("Enrollment");
                                table_cell=new PdfPCell(new Phrase(enrollment));
                                my_report_table.addCell(table_cell);
                                String subject=rs.getString("Subject");
                                table_cell=new PdfPCell(new Phrase(subject));
                                my_report_table.addCell(table_cell);
                                String sdate=rs.getString("sdate");
                                table_cell=new PdfPCell(new Phrase(sdate));
                                my_report_table.addCell(table_cell);
                                String attendance=rs.getString("attendance");
                                table_cell=new PdfPCell(new Phrase(attendance));
                                my_report_table.addCell(table_cell);
                                }
                /* Attach report table to PDF */
                my_pdf_report.add(my_report_table);                       
                my_pdf_report.close();
                break;
                        // pt.executeUpdate();
                        
            }
        }
        catch(SQLException ex)
        {
         Logger.getLogger(StaffLogin.class.getName()).log(Level.SEVERE, null,ex);   
        } catch (DocumentException ex) { 
        Logger.getLogger(StaffLogin.class.getName()).log(Level.SEVERE, null, ex);
    } catch (FileNotFoundException ex) {
        Logger.getLogger(StaffLogin.class.getName()).log(Level.SEVERE, null, ex);
    } 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setState(JFrame.ICONIFIED);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new StaffLogin(subj).setVisible(true);
            }
        });
    }
private void setIcon() {
      setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon1.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
