package attendencelogin;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mr. Faizu
 */


public class RegForm extends javax.swing.JFrame {

    String enroll,subject,name,batch,year,pc,logout,date1,time1,time2;
    Connection con;  
   
    public RegForm() {
        initComponents();
        try {                
                String host = "192.168.1.71";
                con = DriverManager.getConnection("jdbc:mysql://"+host+":3306/information","root","");
                System.out.println("Connected");
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select Enrollment from master1;");
                
                
                while(rs.next()){
                    enroll1.addItem(rs.getString("Enrollment"));
                }
                
                Statement st1 = con.createStatement();
                ResultSet rs1 = st1.executeQuery("select Subject from staff");
                while(rs1.next()){
                    subject1.addItem(rs1.getString("subject"));
                }
        } catch (Exception e) {
            System.out.println(e);
        }
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3min = new javax.swing.JLabel();
        jLabel2close = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Submit = new javax.swing.JButton();
        subject1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        enroll1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        otp = new javax.swing.JLabel();
        otp1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Smart Lab Assistant");

        jLabel3min.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3min.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3min.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3min.setText("-");
        jLabel3min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3minMouseClicked(evt);
            }
        });

        jLabel2close.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2close.setText("X");
        jLabel2close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel3min, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2close, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3min)
                    .addComponent(jLabel2close)
                    .addComponent(jLabel1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 70));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        Submit.setBackground(new java.awt.Color(34, 167, 240));
        Submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Submit.setForeground(new java.awt.Color(0, 255, 204));
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        subject1.setBackground(new java.awt.Color(108, 122, 137));
        subject1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subject1.setForeground(new java.awt.Color(255, 255, 255));
        subject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel11.setText("Subject :");

        enroll1.setBackground(new java.awt.Color(108, 122, 137));
        enroll1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        enroll1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel12.setText("Enrollment ");

        otp.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        otp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        otp1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        otp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otp1.setText("Your OTP :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(otp1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(otp, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subject1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(enroll1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(Submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(enroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(subject1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(otp1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 67, 410, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3minMouseClicked
       this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel3minMouseClicked

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed

        enroll = enroll1.getSelectedItem().toString();
        subject = subject1.getSelectedItem().toString();
        try{
            PreparedStatement pst = con.prepareStatement("Select * from master1 where Enrollment = ?");
            pst.setString(1, enroll);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                name = rs.getString("Name");
                batch = rs.getString("Batch");
                year = rs.getString("Year");
                pc = rs.getString("Pc");                  
            }
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");  
            LocalDateTime now = LocalDateTime.now();
            date1 = dtf.format(now);
            
            DateTimeFormatter dtf1 = DateTimeFormatter.ofPattern("HH:mm:ss");  
            LocalDateTime now1= LocalDateTime.now();
            time1 = dtf1.format(now1);
            
            Random rand = new Random(); 
            int rand_int1 = rand.nextInt(10000);
            otp.setText(Integer.toString(rand_int1));
            PreparedStatement pst1 = con.prepareStatement("insert into stud_info(Enrollment,Name,Subject,Batch,Year,PC,sdate,login,OTP) values(?,?,?,?,?,?,?,?,?)");
            pst1.setString(1,enroll);
            pst1.setString(2,name);
            pst1.setString(3,subject);
            pst1.setString(4,batch);
            pst1.setString(5,year);
            pst1.setString(6,pc);
            pst1.setString(7,date1);
            pst1.setString(8,time1);
            pst1.setInt(9,rand_int1);
            
            pst1.execute();
          
        }catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_SubmitActionPerformed

    private void subject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject1ActionPerformed

    private void jLabel2closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2closeMouseClicked
        
        
        DateTimeFormatter dtf1 = DateTimeFormatter.ofPattern("HH:mm:ss");  
        LocalDateTime now1= LocalDateTime.now();
        time2 = dtf1.format(now1);
        
        try {        
                PreparedStatement pst = con.prepareStatement("update stud_info set logout=? where Enrollment = "+enroll);
                pst.setString(1, time2);
                pst.execute();
        } catch (Exception e) {
        }
        System.exit(0);
    }//GEN-LAST:event_jLabel2closeMouseClicked

    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        
  
            java.awt.EventQueue.invokeLater(new Runnable(){
                public void run(){
                new RegForm().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JComboBox<String> enroll1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2close;
    private javax.swing.JLabel jLabel3min;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel otp;
    private javax.swing.JLabel otp1;
    private javax.swing.JComboBox<String> subject1;
    // End of variables declaration//GEN-END:variables

}

